### PR TITLE
Feat/ruff reformat

### PR DESCRIPTION
**Pull request by ConnorBaker**
PR based on #1

### CODE REVIEW

**Comment by ConnorBaker** [comment]
Apologies, this was meant to be on my local branch until I had stabilized the PRs.

**Comment by Simarilius-uk** [comment]
I know you closed it, but why does it want to change all ' to " ?

**Comment by Simarilius-uk** [comment]
They look ugly, they require shift to type and mess with my head (I work on mac and windows so its different keystrokes on the different systems)  cant say I've ever had an issue distinguishing between '' and " in VS and the code formatting kinda makes that irrelevant anyways, as if it was an unclosed " it would color everything after it.
PEP257 actually uses singles around the none docstrings in its examples, so I think the black code style has fuxked up there. PEP8 which is the actual generic style guide just says pick one and stick to it, my vote is very much for singles. https://peps.python.org/pep-0008/#string-quotes

**Comment by Simarilius-uk** [comment]
Hoping that didnt come across as grumpy, very much welcome the input and effort, would just rather this bit of it was to standardise on single quotes not double :)

**Comment by ConnorBaker** [comment]
No worries! I totally understand the preference -- IIRC there's also a flag to change the setting Ruff/Black uses.

Unfortunately, I got busy again with work so it's unlikely I'll be able to progress on the refactorings I had in mind :(

For what it's worth, I do still recommend adding a formatter/linter to the CI, if only to ensure code is consistently styled and common footguns are left unloaded :)

**Pull request closed without merging**
